const swaggerAutogen = require("swagger-autogen")();
const port = process.env.PORT || 3001;
const doc = {
  info: {
    version: "1.0.0",
    title: "Poseidon API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: `localhost:${port}`,
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  // Cho nay define section trong swagger, sau do add tag tuong ung trong API
  tags: [
    // {
    //   name: "User",
    //   description: "Endpoints",
    // },
  ],
  // Cho nay define authorization settings
  securityDefinitions: {
    api_key: {
      type: "apiKey",
      name: "api_key",
      in: "header",
    },
    petstore_auth: {
      type: "oauth2",
      authorizationUrl: "https://petstore.swagger.io/oauth/authorize",
      flow: "implicit",
      scopes: {
        read_pets: "read your pets",
        write_pets: "modify pets in your account",
      },
    },
  },
  // Cho nay define model reference
  definitions: {
    GenerateTokenRequest: {
      $token: "SomeSpecialString",
      $pageId: "a$b%som3thing",
    },
    SignUpRequest: {
      $username: "username",
      $password: "password",
    },
    createAreaModel: {
      $name: "Ten Khu Vuc",
      ownerId: [0986323066],
      $location: "Ha Noi",
    },
  },
};

const outputFile = "./swagger_output.json";
const endpointsFiles = ["./index.js"];

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require("./index.js"); // Your project's root file
});
